name: Lux

on:
    push:
      branches: [ 'main' ]
    pull_request:
      branches: [ 'main' ]

jobs:
  Lux:
    name: clang-format check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        
      - name: Run clang-format style check
        uses: jidicula/clang-format-action@f62da5e3d3a2d88ff364771d9d938773a618ab5e  # @v4.11.0
        id: clang-format
        continue-on-error: true
        with:
          clang-format-version: '17'
