name: Lux

on:
    push:
      branches: [ 'main' ]
    pull_request:
      branches: [ 'main' ]

defaults:
  run:
    working-directory: src

jobs:
  Lux:
    name: compile check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: Default
      run: make default

    - name: Release
      run: make release
