name: Lux

on:
    push:
      branches: [ 'main' ]
    pull_request:
      branches: [ 'main' ]

defaults:
  run:
    working-directory: src

jobs:
  Lux:
    name: compile check

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3

    # - name: Set up build tools
    #   run: |
    #     if [ $RUNNER_OS == 'Ubuntu' ]; then
    #       sudo apt-get update
    #       sudo apt-get install -y build-essential
    #     elif [ $RUNNER_OS == 'macOS' ]; then
    #       brew install make
    #     elif [ $RUNNER_OS == 'Windows' ]; then
    #       choco install make
    #     fi

    - name: Default
      run: make default

    - name: Release
      run: make release
